# Generated by Django 3.0.5 on 2021-09-27 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210927_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_facebook',
            new_name='social_twitter',
        ),
    ]
